<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Главная страница</title>
</head>
<body>
    <h1>Выберите таблицу:</h1>
    <ul>
        <li><a href="/finassets">Финансовые инструменты (FinAsset)</a></li>
        <li><a href="/tikers">Тикеры (Tiker)</a></li>
        <li><a href="/securities">Акции (Security)</a></li>
        <li><a href="/bonds">Облигации (Bond)</a></li>
    </ul>
</body>
</html>
